---
title: Project 2
hidedate: true
output:
  html_document: default
  pdf_document: default
---
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
                      tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```
##Samantha Snyder sms7265  


#####Introduction
*My dataset is called BirdNest and contains variables that measure species and nest characteristics for North American passerines (perching birds). There are 84 observations including 12 variables. Species denotes the Latin species name, Common is the common species name, Length is the mean body length for each species in cm, Nesttype is the type of nest (various factors), Location is the location of the nest by region, No.eggs is the mean number of eggs, Color is color of the eggs (0=solid, 1=speckled/spotted), Incubate is the mean time in days that the species incubates eggs in the nest, Nestling is the mean time in days that the species cares for the babies in the nest until they are able to fly, Totcare is the total time taken to care for the babies (Incubate+Nestling), and Closed. is whether the nest is open or closed. This dataset was very interesting to me and I feel like I have learned a great deal about bird nests which is fun!*

#####Manova
```{R}
library(Stat2Data)
library (tidyverse)
data(BirdNest)
BirdNest<-BirdNest%>%na.omit()%>%select(-Page)
head(BirdNest)
str(BirdNest)
BirdNest$Species<-as.character(BirdNest$Species)
BirdNest$Common<-as.character(BirdNest$Common)
library(rstatix)
BirdNest$Nesttype<-as.character(BirdNest$Nesttype)
group <- BirdNest$Common 
DVs <- BirdNest %>% select(Length,No.eggs,Incubate,Nestling)

#Test multivariate normality for each group (null: assumption met)
sapply(split(DVs,group), mshapiro_test)

man1<-manova(cbind(Length, No.eggs,Incubate,Nestling)~Nesttype, data=BirdNest)

summary(man1)
summary.aov(man1)


pairwise.t.test(BirdNest$Incubate, BirdNest$Nesttype, p.adj = "none") 
pairwise.t.test(BirdNest$No.eggs, BirdNest$Nesttype, p.adj = "none") 
pairwise.t.test(BirdNest$Length, BirdNest$Nesttype, p.adj = "none") 
pairwise.t.test(BirdNest$Nestling, BirdNest$Nesttype, p.adj = "none") 
 
``` 

*84 pairwise t tests were performed that compared the different types of nests with the other levels no.eggs, nestling, length, and incubate. The probability that we have made a type I error is 0.987 which was found by calculating 1-.95^84. The boneferroni adjusted significance level is .000595 and the post hoc tests that were significant that are no longer significant are spherical and saucer. MANOVA assumptions of Random samples and independent observations are likely met, multivariate normality of DVs is likely not met, homogeneity of within-group covariance matrices is likely met, linear relationships among DVs is likely not met, no extreme univariate or multivariate outliers is likely met, and no multicollinearity is likely met.*

#####Randomization Test
```{R}
ggplot(BirdNest,aes(Length,fill=Color))+geom_histogram(bins=6.5)+
  facet_wrap(~Color,ncol=2)+theme(legend.position="none")
BirdNest%>%group_by(Color)%>%
  summarize(means=mean(Length))%>%summarize(`mean_diff`=diff(means))

rand_dist<-vector() 

for(i in 1:5000){
new<-data.frame(Color=sample(BirdNest$Color),Length=BirdNest$Length) 
rand_dist[i]<-mean(new[new$Color==1,]$Length)-   
              mean(new[new$Color==0,]$Length)}

{hist(rand_dist,main="",ylab=""); abline(v = c(-.0595, .0595),col="red")}
mean(rand_dist>.0595 | rand_dist< -.0595)
```

*The null hypothesis is that there are no differences (mean difference is equal to 0) between the mean length of bird between solid/plain colored eggs and speckled/spotted colored eggs. The alternative hypothesis is that there is a difference (mean difference does not equal 0) between the mean length of bird between solid/plain colored eggs and speckled/spotted colored eggs. The mean difference was found to be 0.0595 which indicates that we fail to reject the null hypothesis that there are no differences in mean length between egg colors. The p-value was found to be .9794 which indicates that the results that were found are not significant and are very likely due to chance.*


#####Linear Regression
```{R}
library(sandwich)
library(lmtest) 
BirdNest$Incubate_c <- BirdNest$Incubate - mean(BirdNest$Incubate)
mean(BirdNest$Incubate)
fit1<-lm(Length~Color*Incubate_c, data=BirdNest) 
summary(fit1)
BirdNest %>% ggplot(aes(Length, Incubate, color = Color)) + geom_point() + geom_smooth(method = "lm", se = FALSE, fullrange = TRUE)

bptest(fit1)
resids<-lm(Length~Color*Incubate, data=BirdNest)$residuals
fitted<-lm(Length~Color*Incubate, data=BirdNest)$fitted.value
ggplot()+geom_histogram(aes(resids, bin=10))
ggplot()+geom_point(aes(fitted,resids))
resids<-fit1$residuals
fitvals<-fit1$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color='red')
ggplot()+geom_histogram(aes(resids), bins=20)
ggplot()+geom_qq(aes(sample=resids))+geom_qq()
shapiro.test(resids)
coeftest(fit1, vcov = vcovHC(fit1))

boot_dat<- sample_frac(BirdNest, replace=T)


samp_distn<-replicate(5000, {
  boot_dat <- sample_frac(BirdNest, replace=T) 
  fit1 <- lm(Length~Color*Incubate, data=boot_dat) 
  coef(fit1) 
}) 
 

samp_distn %>% t %>% as.data.frame %>% summarize_all(sd) 

```
*For the intercept, 17.608 is the mean/predicted length for solid/plain colored eggs with a mean incubation time of 13.35. For birds with an average incubation time, speckled/spotted eggs have a predicted length that is 0.0227 greater (t=.017, p=.9867). For every one unit increase in incubation time, predicted length goes up by 0.015 for speckled/spotted eggs (t=.016, p=.9872). The slope for length on incubate is 1.736 greater for speckled or spotted eggs than for solid colored eggs (t=1.77, p=.0806). The assumptions of homoskedasticity, linearity, and normality all appear to be met.  There are no significant results after running the linear regression model.This model explains .2271 proportion of the variation of the outcome (adjusted R-squared). After performing the robust standard errors, compared to the original SEs, the SEs decreased by a small amount for each value while the p-values remained about the same for color and incubate_c but slightly decreased for the interaction. None of the results are significant, although the interaction is very close to being significant. After performing the bootstrapped SEs, the SE for color and the intercept is much higher than the original SE, while the incubate and color:incubate SEs are about the same as the original SEs.*

#####Fitted Logistic Regression

```{R}
library(glmnet)
BirdNest1<-BirdNest%>%mutate(y=ifelse(Color=="1",1,0))
fitlog<-glm(y~Nesttype + Location,data=BirdNest1,family=binomial(link="logit"))
coeftest(fitlog)
exp(coef(fitlog))
summary(fitlog)
prob<-predict(fitlog,type="response") 
pred<-ifelse(prob>.5,1,0)
table(truth=BirdNest1$Color, prediction=pred)%>%addmargins
class_diag <- function(probs,truth){
#CONFUSION MATRIX: CALCULATE ACCURACY, TPR, TNR, PPV

if(is.character(truth)==TRUE) truth<-as.factor(truth)
if(is.numeric(truth)==FALSE & is.logical(truth)==FALSE) truth<-as.numeric(truth)-1

tab<-table(factor(probs>.5,levels=c("FALSE","TRUE")),factor(truth, levels=c(0,1)))
acc=sum(diag(tab))/sum(tab)
sens=tab[2,2]/colSums(tab)[2]
spec=tab[1,1]/colSums(tab)[1]
ppv=tab[2,2]/rowSums(tab)[2]
f1=2*(sens*ppv)/(sens+ppv)

#CALCULATE EXACT AUC
ord<-order(probs, decreasing=TRUE)
probs <- probs[ord]; truth <- truth[ord]

TPR=cumsum(truth)/max(1,sum(truth)) 
FPR=cumsum(!truth)/max(1,sum(!truth))

dup<-c(probs[-1]>=probs[-length(probs)], FALSE)
TPR<-c(0,TPR[!dup],1); FPR<-c(0,FPR[!dup],1)
n <- length(TPR)
auc<- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

data.frame(acc,sens,spec,ppv,f1,auc)
}
class_diag(prob,BirdNest$Color)
ggplot(BirdNest1, aes(x=Nesttype, y=Location,group=Color))+geom_point(aes(color=Color))+
geom_smooth(method="lm",formula=y~1,se=F,fullrange=T,aes(color=Color))+
theme(legend.position=c(.9,.19))+xlab("")
BirdNest1$logit<-predict(fitlog)

BirdNest1$Color<-as.factor(BirdNest1$Color)
BirdNest1%>%ggplot()+geom_density(aes(logit,color=Color,fill=Color), alpha=.4)+
  theme(legend.position=c(.85,.85))+geom_vline(xintercept=0)+xlab("logit (log-odds)")+
  geom_rug(aes(logit,color=Color))
library(plotROC) 

ROCplot<-ggplot(fitlog)+geom_roc(aes(d=y,m=prob), n.cuts=0) 

ROCplot


calc_auc(ROCplot)


```
*The intercept indicates that the odds of having a burrow nest type and bank location with solid colored eggs are 1.17x10^-9. Controlling for location, the odds of having spotted/speckled eggs are 5.03x10^17 times more likely for cavity nests, the odds of spotted/speckled eggs are 7.302x10^17 times more likely for a cup nest, the odds of spotted/speckled eggs are 3.703x10^9 times more likely for a pendant nest type, etc. When controlling for nest type, the odds of having spotted/speckled eggs are 2.7x10^-10 times less likely for bridge locations, the odds of having speckled/spotted eggs are 7.79x10^7 more likely for building locations, the odds of having spotted/speckled eggs are 1.37x10^-18 less likely for cliff locations, etc. The accuracy is .892, sensitivity (true positive rate) is .986, specificity (true negative rate) is .429, precision is .895, and AUC is .854. These values are all close to 1 and indicate that the probability of detecting the true color of the egg (speckled/spotted) is high as well as the probability of predicting eggs that are not speckled/spotted. The precision value is the proportion of eggs that are classified as speckled/spotted that actually are that color. The ROC curve give us the area under the curve, which is .854 and is a good predictor. The AUC value is the probability that a randomly selected bird with spotted/speckled eggs has a higher predicted probability than a randomly selected bird with solid colored eggs.*

#####Logistic Regression part 2
```{R}
BirdNest1<-BirdNest1%>%select(-logit, -Color)
whoofit<-glm(y~Nestling + Incubate + Location + Nesttype + Length,data=BirdNest1,family=binomial(link="logit"))
prob<-predict(whoofit,type="response") 
pred<-ifelse(prob>.5,1,0)
table(truth=BirdNest1$y, prediction=pred)%>%addmargins
class_diag(prob,BirdNest1$y)
library(glmnet)
set.seed(1234)
y<-as.matrix(BirdNest1$y) 
bird_preds<-model.matrix(y~.,data=BirdNest1)[,-1] 
head(bird_preds)
head(BirdNest1)
str(BirdNest1)

class_diag <- function(probs,truth){
#CONFUSION MATRIX: CALCULATE ACCURACY, TPR, TNR, PPV

if(is.character(truth)==TRUE) truth<-as.factor(truth)
if(is.numeric(truth)==FALSE & is.logical(truth)==FALSE) truth<-as.numeric(truth)-1

tab<-table(factor(probs>.5,levels=c("FALSE","TRUE")),factor(truth, levels=c(0,1)))
acc=sum(diag(tab))/sum(tab)
sens=tab[2,2]/colSums(tab)[2]
spec=tab[1,1]/colSums(tab)[1]
ppv=tab[2,2]/rowSums(tab)[2]
f1=2*(sens*ppv)/(sens+ppv)

#CALCULATE EXACT AUC
ord<-order(probs, decreasing=TRUE)
probs <- probs[ord]; truth <- truth[ord]

TPR=cumsum(truth)/max(1,sum(truth)) 
FPR=cumsum(!truth)/max(1,sum(!truth))

dup<-c(probs[-1]>=probs[-length(probs)], FALSE)
TPR<-c(0,TPR[!dup],1); FPR<-c(0,FPR[!dup],1)
n <- length(TPR)
auc<- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

data.frame(acc,sens,spec,ppv,f1,auc)
}
set.seed(1234)
k=10
data <- BirdNest1 %>% sample_frac 
folds <- ntile(1:nrow(data),n=10) 
diags<-NULL
for(i in 1:k){
train <- data[folds!=i,] 
test <- data[folds==i,]
truth <- test$y 
fit <- glm(y~(.)^2, data=train, family="binomial")
probs <- predict(whoofit, newdata=test, type="response")
diags<-rbind(diags,class_diag(probs,truth))
}
summarize_all(diags,mean)

cv <- cv.glmnet(bird_preds,y, family="binomial") 


{plot(cv$glmnet.fit, "lambda", label=TRUE); abline(v = log(cv$lambda.1se)); abline(v = log(cv$lambda.min),lty=2)}

cv<-cv.glmnet(bird_preds,y,family="binomial")
lasso_fit<-glmnet(bird_preds,y,family="binomial",lambda=cv$lambda.1se)
coef(lasso_fit)
probs<-predict(lasso_fit, bird_preds, type="response")
truth<-BirdNest1$y

class_diag <- function(probs,truth){
  tab<-table(factor(probs>.5,levels=c("FALSE","TRUE")),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]
  f1=2*(sens*ppv)/(sens+ppv)

  if(is.numeric(truth)==FALSE & is.logical(truth)==FALSE) truth<-as.numeric(truth)-1
  
  ord<-order(probs, decreasing=TRUE)
  probs <- probs[ord]; truth <- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup<-c(probs[-1]>=probs[-length(probs)], FALSE)
  TPR<-c(0,TPR[!dup],1); FPR<-c(0,FPR[!dup],1)
  n <- length(TPR)
  auc<- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,f1,auc)
}
class_diag(prob,BirdNest1$y)
table(prediction=as.numeric(prob > 0.5), truth=BirdNest1$y) %>% addmargins


set.seed(1234)
k=5
poke_mybelly <- BirdNest1 %>% mutate(Locationsnag=ifelse(Location=="snag",1,0),
                               )

whoabro <- poke_mybelly %>% sample_frac 
folds <- ntile(1:nrow(whoabro),n=5) 


diags<-NULL
for(i in 1:k){
  train <- whoabro[folds!=i,] 
  test <- whoabro[folds==i,] 
  truth <- test$y
  
  fit <- glm(y~Locationsnag, 
             data=train, family="binomial")
  probs <- predict(fit, newdata=test, type="response")
  
  diags<-rbind(diags,class_diag(probs,truth))
}

summarize_all(diags,mean)
```

*For the in-sample model, the accuracy is .892, sensitivity is .986, specificity is .429, precision is .895, and auc is .91. The sensitivity indicates the probability of detecting the true color of the egg (speckled/spotted) is high when comparing nestling, incubate, length, nest type, and location while the probability of predicting eggs that are not speckled/spotted are not good since the specificity is so low. The precision value is the proportion of eggs that are classified as speckled/spotted that actually are that color when looking at the other variables. The AUC value is a great predictor and shows the probability that a randomly selected bird with spotted/speckled eggs has a higher predicted probability than a randomly selected bird with solid colored eggs. After performing the 10-fold cv with the in-sample model, the out-of-sample classification diagnostics include an accuracy of .892, sensitivity of .896, precision of.902, and an auc of .938. All of the values are very similar while the AUC went up slightly and is still a great predictor. This indicates that there is not evidence of overfitting in the model. The only variable that is retained after performing lasso is the snag location. For the 10-fold cv using only the snag location, the accuracy is .843, sensitivity is .985, specificity is .117, precision is .849, and auc is .551. The sensitivity indicates that the probability of detecting spotted/speckled that are truly that color is very high when looking only at the snag location. Specificity, on the other hand, is very low which indicates that predicting the probability of eggs that are not speckled/spotted is poor when looking at the snag location. The precision is pretty good which indicates that the proportion of speckled/spotted eggs that get classified as such are relatively high. The auc value is very low which indicates that this model is a bad predictor of egg color when looking at snag location. These values are all much lower (except for the sensitivity) than the out-of-sample diagnostics which indicates that there is evidence of overfitting in this model. *

```{R, echo=F}
## DO NOT DELETE THIS CHUNK!
sessionInfo()
Sys.time()
Sys.info()
```

